eureka:
  instance:
    # hostname: localhost
    hostname: discovery-server
  client:
    service-url:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
spring:
  cloud:
    config:
      override-system-properties: false