eureka:
  instance:
    # hostname: localhost
    hostname: discovery-server
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      # defaultZone: http://discovery-server:8761/eureka/
spring:
  cloud:
    config:
      override-system-properties: true