eureka:
  instance:
    # hostname: localhost
    # hostname: discovery-server
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      # defaultZone: http://discovery-server:8761/eureka/
spring:
  cloud:
    config:
      override-system-properties: true